name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for changelog generation
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.1 

      - name: Get module name
        id: get_module
        run: |
          MODULE_NAME=$(grep -m 1 "module" go.mod | awk '{print $2}')
          echo "module_name=$MODULE_NAME" >> $GITHUB_OUTPUT
          echo "Using module name: $MODULE_NAME"

      - name: Build for multiple platforms
        run: |
          mkdir -p builds
          # Extract version from tag (removes 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building version: $VERSION"
          
          # Get current timestamp
          BUILDTIME=$(date -u '+%Y-%m-%d %H:%M:%S')
          echo "Build time: $BUILDTIME"
          
          # Get current commit hash
          COMMIT=$(git rev-parse HEAD)
          echo "Commit: $COMMIT"
          
          # Build for different platforms with simplified ldflags
          echo "Building macOS (amd64)..."
          GOOS=darwin GOARCH=amd64 go build \
            -ldflags="-X 'main.Version=$VERSION' -X 'main.BuildTime=$BUILDTIME' -X 'main.Commit=$COMMIT'" \
            -o builds/ics-cli-macos-amd64
          
          echo "Building macOS (arm64)..."
          GOOS=darwin GOARCH=arm64 go build \
            -ldflags="-X 'main.Version=$VERSION' -X 'main.BuildTime=$BUILDTIME' -X 'main.Commit=$COMMIT'" \
            -o builds/ics-cli-macos-arm64
          
          echo "Building Linux (amd64)..."
          GOOS=linux GOARCH=amd64 go build \
            -ldflags="-X 'main.Version=$VERSION' -X 'main.BuildTime=$BUILDTIME' -X 'main.Commit=$COMMIT'" \
            -o builds/ics-cli-linux-amd64
          
          echo "Building Windows (amd64)..."
          GOOS=windows GOARCH=amd64 go build \
            -ldflags="-X 'main.Version=$VERSION' -X 'main.BuildTime=$BUILDTIME' -X 'main.Commit=$COMMIT'" \
            -o builds/ics-cli-windows-amd64.exe
            
          # Generate checksums
          cd builds/
          sha256sum ics-cli-* > SHA256SUMS.txt
          cd ..

      - name: Generate Release Notes
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            # If there's no previous tag, include all commits
            git log --pretty=format:"* %s (%h)" > RELEASE_NOTES.md
          else
            # Generate changelog from previous tag to current
            echo "## Changes since $PREV_TAG" > RELEASE_NOTES.md
            echo "" >> RELEASE_NOTES.md
            git log --pretty=format:"* %s (%h)" $PREV_TAG..HEAD >> RELEASE_NOTES.md
          fi
          
          echo "" >> RELEASE_NOTES.md
          echo "## Installation" >> RELEASE_NOTES.md
          echo "Download the appropriate binary for your platform and add it to your PATH." >> RELEASE_NOTES.md
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            builds/ics-cli-macos-amd64
            builds/ics-cli-macos-arm64
            builds/ics-cli-linux-amd64
            builds/ics-cli-windows-amd64.exe
            builds/SHA256SUMS.txt
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

